ldc_bloggle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LDCBloggleBundle:Default:index }

ldc_bloggle_create:
    pattern:  /create
    defaults: { _controller: LDCBloggleBundle:Default:create }

ldc_bloggle_blog:
    pattern:  /blog
    defaults: { _controller: LDCBloggleBundle:Default:blog }

ldc_bloggle_purge:
    pattern:  /purge
    defaults: { _controller: LDCBloggleBundle:Default:purge }
