ldc_bloggle_homepage:
    pattern:  /
    defaults: { _controller: LDCBloggleBundle:Blog:index }

ldc_bloggle_post:
    pattern:  /blog/{title}/post
    defaults: { _controller: LDCBloggleBundle:Post:post }

ldc_bloggle_posted:
    pattern:  /blog/{title}/posted
    defaults: { _controller: LDCBloggleBundle:Post:posted }

ldc_bloggle_newblog:
    pattern:  /newblog
    defaults: { _controller: LDCBloggleBundle:Blog:new}

ldc_bloggle_created:
    pattern:  /created
    defaults: { _controller: LDCBloggleBundle:Blog:created}

ldc_bloggle_blog:
    pattern:  /blog/{title}
    defaults: { _controller: LDCBloggleBundle:Blog:blog }
