ldc_account_login:
    pattern:  /login
    defaults: { _controller: LDCAccountBundle:Security:login }

ldc_account_login_check:
    pattern:  /login_check
    defaults: { _controller: LDCAccountBundle:Security:check }

ldc_account_register:
    pattern:  /register
    defaults: { _controller: LDCAccountBundle:Account:register }

ldc_account_create:
    pattern:  /create
    defaults: { _controller: LDCAccountBundle:Account:create }
