ldc_account_register:
    pattern:  /register
    defaults: { _controller: LDCAccountBundle:Account:register }

ldc_account_create:
    pattern:  /create
    defaults: { _controller: LDCAccountBundle:Account:create }
